In [2]:
# TASK 1
import numpy as np
HR=np.arange(1,501)
Finance=np.arange(501,1001)
IT=np.arange(1001,1501)
Sales=np.arange(1501,2001)
print(HR)
print(Finance)
print(IT)
print(Sales)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252
 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270
 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288
 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306
 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324
 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342
 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360
 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378
 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396
 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414
 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432
 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449 450
 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467 468
 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485 486
 487 488 489 490 491 492 493 494 495 496 497 498 499 500]
[ 501  502  503  504  505  506  507  508  509  510  511  512  513  514
  515  516  517  518  519  520  521  522  523  524  525  526  527  528
  529  530  531  532  533  534  535  536  537  538  539  540  541  542
  543  544  545  546  547  548  549  550  551  552  553  554  555  556
  557  558  559  560  561  562  563  564  565  566  567  568  569  570
  571  572  573  574  575  576  577  578  579  580  581  582  583  584
  585  586  587  588  589  590  591  592  593  594  595  596  597  598
  599  600  601  602  603  604  605  606  607  608  609  610  611  612
  613  614  615  616  617  618  619  620  621  622  623  624  625  626
  627  628  629  630  631  632  633  634  635  636  637  638  639  640
  641  642  643  644  645  646  647  648  649  650  651  652  653  654
  655  656  657  658  659  660  661  662  663  664  665  666  667  668
  669  670  671  672  673  674  675  676  677  678  679  680  681  682
  683  684  685  686  687  688  689  690  691  692  693  694  695  696
  697  698  699  700  701  702  703  704  705  706  707  708  709  710
  711  712  713  714  715  716  717  718  719  720  721  722  723  724
  725  726  727  728  729  730  731  732  733  734  735  736  737  738
  739  740  741  742  743  744  745  746  747  748  749  750  751  752
  753  754  755  756  757  758  759  760  761  762  763  764  765  766
  767  768  769  770  771  772  773  774  775  776  777  778  779  780
  781  782  783  784  785  786  787  788  789  790  791  792  793  794
  795  796  797  798  799  800  801  802  803  804  805  806  807  808
  809  810  811  812  813  814  815  816  817  818  819  820  821  822
  823  824  825  826  827  828  829  830  831  832  833  834  835  836
  837  838  839  840  841  842  843  844  845  846  847  848  849  850
  851  852  853  854  855  856  857  858  859  860  861  862  863  864
  865  866  867  868  869  870  871  872  873  874  875  876  877  878
  879  880  881  882  883  884  885  886  887  888  889  890  891  892
  893  894  895  896  897  898  899  900  901  902  903  904  905  906
  907  908  909  910  911  912  913  914  915  916  917  918  919  920
  921  922  923  924  925  926  927  928  929  930  931  932  933  934
  935  936  937  938  939  940  941  942  943  944  945  946  947  948
  949  950  951  952  953  954  955  956  957  958  959  960  961  962
  963  964  965  966  967  968  969  970  971  972  973  974  975  976
  977  978  979  980  981  982  983  984  985  986  987  988  989  990
  991  992  993  994  995  996  997  998  999 1000]
[1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014
 1015 1016 1017 1018 1019 1020 1021 1022 1023 1024 1025 1026 1027 1028
 1029 1030 1031 1032 1033 1034 1035 1036 1037 1038 1039 1040 1041 1042
 1043 1044 1045 1046 1047 1048 1049 1050 1051 1052 1053 1054 1055 1056
 1057 1058 1059 1060 1061 1062 1063 1064 1065 1066 1067 1068 1069 1070
 1071 1072 1073 1074 1075 1076 1077 1078 1079 1080 1081 1082 1083 1084
 1085 1086 1087 1088 1089 1090 1091 1092 1093 1094 1095 1096 1097 1098
 1099 1100 1101 1102 1103 1104 1105 1106 1107 1108 1109 1110 1111 1112
 1113 1114 1115 1116 1117 1118 1119 1120 1121 1122 1123 1124 1125 1126
 1127 1128 1129 1130 1131 1132 1133 1134 1135 1136 1137 1138 1139 1140
 1141 1142 1143 1144 1145 1146 1147 1148 1149 1150 1151 1152 1153 1154
 1155 1156 1157 1158 1159 1160 1161 1162 1163 1164 1165 1166 1167 1168
 1169 1170 1171 1172 1173 1174 1175 1176 1177 1178 1179 1180 1181 1182
 1183 1184 1185 1186 1187 1188 1189 1190 1191 1192 1193 1194 1195 1196
 1197 1198 1199 1200 1201 1202 1203 1204 1205 1206 1207 1208 1209 1210
 1211 1212 1213 1214 1215 1216 1217 1218 1219 1220 1221 1222 1223 1224
 1225 1226 1227 1228 1229 1230 1231 1232 1233 1234 1235 1236 1237 1238
 1239 1240 1241 1242 1243 1244 1245 1246 1247 1248 1249 1250 1251 1252
 1253 1254 1255 1256 1257 1258 1259 1260 1261 1262 1263 1264 1265 1266
 1267 1268 1269 1270 1271 1272 1273 1274 1275 1276 1277 1278 1279 1280
 1281 1282 1283 1284 1285 1286 1287 1288 1289 1290 1291 1292 1293 1294
 1295 1296 1297 1298 1299 1300 1301 1302 1303 1304 1305 1306 1307 1308
 1309 1310 1311 1312 1313 1314 1315 1316 1317 1318 1319 1320 1321 1322
 1323 1324 1325 1326 1327 1328 1329 1330 1331 1332 1333 1334 1335 1336
 1337 1338 1339 1340 1341 1342 1343 1344 1345 1346 1347 1348 1349 1350
 1351 1352 1353 1354 1355 1356 1357 1358 1359 1360 1361 1362 1363 1364
 1365 1366 1367 1368 1369 1370 1371 1372 1373 1374 1375 1376 1377 1378
 1379 1380 1381 1382 1383 1384 1385 1386 1387 1388 1389 1390 1391 1392
 1393 1394 1395 1396 1397 1398 1399 1400 1401 1402 1403 1404 1405 1406
 1407 1408 1409 1410 1411 1412 1413 1414 1415 1416 1417 1418 1419 1420
 1421 1422 1423 1424 1425 1426 1427 1428 1429 1430 1431 1432 1433 1434
 1435 1436 1437 1438 1439 1440 1441 1442 1443 1444 1445 1446 1447 1448
 1449 1450 1451 1452 1453 1454 1455 1456 1457 1458 1459 1460 1461 1462
 1463 1464 1465 1466 1467 1468 1469 1470 1471 1472 1473 1474 1475 1476
 1477 1478 1479 1480 1481 1482 1483 1484 1485 1486 1487 1488 1489 1490
 1491 1492 1493 1494 1495 1496 1497 1498 1499 1500]
[1501 1502 1503 1504 1505 1506 1507 1508 1509 1510 1511 1512 1513 1514
 1515 1516 1517 1518 1519 1520 1521 1522 1523 1524 1525 1526 1527 1528
 1529 1530 1531 1532 1533 1534 1535 1536 1537 1538 1539 1540 1541 1542
 1543 1544 1545 1546 1547 1548 1549 1550 1551 1552 1553 1554 1555 1556
 1557 1558 1559 1560 1561 1562 1563 1564 1565 1566 1567 1568 1569 1570
 1571 1572 1573 1574 1575 1576 1577 1578 1579 1580 1581 1582 1583 1584
 1585 1586 1587 1588 1589 1590 1591 1592 1593 1594 1595 1596 1597 1598
 1599 1600 1601 1602 1603 1604 1605 1606 1607 1608 1609 1610 1611 1612
 1613 1614 1615 1616 1617 1618 1619 1620 1621 1622 1623 1624 1625 1626
 1627 1628 1629 1630 1631 1632 1633 1634 1635 1636 1637 1638 1639 1640
 1641 1642 1643 1644 1645 1646 1647 1648 1649 1650 1651 1652 1653 1654
 1655 1656 1657 1658 1659 1660 1661 1662 1663 1664 1665 1666 1667 1668
 1669 1670 1671 1672 1673 1674 1675 1676 1677 1678 1679 1680 1681 1682
 1683 1684 1685 1686 1687 1688 1689 1690 1691 1692 1693 1694 1695 1696
 1697 1698 1699 1700 1701 1702 1703 1704 1705 1706 1707 1708 1709 1710
 1711 1712 1713 1714 1715 1716 1717 1718 1719 1720 1721 1722 1723 1724
 1725 1726 1727 1728 1729 1730 1731 1732 1733 1734 1735 1736 1737 1738
 1739 1740 1741 1742 1743 1744 1745 1746 1747 1748 1749 1750 1751 1752
 1753 1754 1755 1756 1757 1758 1759 1760 1761 1762 1763 1764 1765 1766
 1767 1768 1769 1770 1771 1772 1773 1774 1775 1776 1777 1778 1779 1780
 1781 1782 1783 1784 1785 1786 1787 1788 1789 1790 1791 1792 1793 1794
 1795 1796 1797 1798 1799 1800 1801 1802 1803 1804 1805 1806 1807 1808
 1809 1810 1811 1812 1813 1814 1815 1816 1817 1818 1819 1820 1821 1822
 1823 1824 1825 1826 1827 1828 1829 1830 1831 1832 1833 1834 1835 1836
 1837 1838 1839 1840 1841 1842 1843 1844 1845 1846 1847 1848 1849 1850
 1851 1852 1853 1854 1855 1856 1857 1858 1859 1860 1861 1862 1863 1864
 1865 1866 1867 1868 1869 1870 1871 1872 1873 1874 1875 1876 1877 1878
 1879 1880 1881 1882 1883 1884 1885 1886 1887 1888 1889 1890 1891 1892
 1893 1894 1895 1896 1897 1898 1899 1900 1901 1902 1903 1904 1905 1906
 1907 1908 1909 1910 1911 1912 1913 1914 1915 1916 1917 1918 1919 1920
 1921 1922 1923 1924 1925 1926 1927 1928 1929 1930 1931 1932 1933 1934
 1935 1936 1937 1938 1939 1940 1941 1942 1943 1944 1945 1946 1947 1948
 1949 1950 1951 1952 1953 1954 1955 1956 1957 1958 1959 1960 1961 1962
 1963 1964 1965 1966 1967 1968 1969 1970 1971 1972 1973 1974 1975 1976
 1977 1978 1979 1980 1981 1982 1983 1984 1985 1986 1987 1988 1989 1990
 1991 1992 1993 1994 1995 1996 1997 1998 1999 2000]

In [3]:
# TASK 2
HR_salary=np.random.randint(25000,50001,500)
print('HR salary=',HR_salary)
print()
Finance_salary=HR_salary*1.25
print('Finance salary=',Finance_salary)
print()
Sales_salary=Finance_salary*0.5
print('Sales salary=',Sales_salary)
print()
IT_salary=HR_salary+5000
print('IT salary=',IT_salary)

HR salary= [47208 47635 25508 38587 38353 42873 42190 33724 48513 46946 35005 37362
 37132 33416 25545 48669 37495 28807 38304 36218 35940 27310 47140 48499
 35494 42583 34909 40774 42126 27140 26997 48431 34305 27543 45672 26244
 35393 42342 47376 35053 25430 43002 37496 29737 43015 46184 36629 26325
 25244 49966 40929 39034 43351 31464 34701 42191 34725 30446 40640 26740
 43169 36869 27945 49313 28564 49084 47747 27090 42680 30586 37547 32591
 33486 25793 42420 29657 44773 27699 39325 29716 32163 30076 31420 36762
 31277 36735 49030 43998 35440 26200 47911 47999 29272 45025 39146 43029
 32949 44048 40679 31039 30001 29977 34836 35678 48420 49458 47120 48329
 39488 39107 45888 36673 32720 29042 27664 48421 36176 37891 26926 34512
 36623 27249 49833 29235 26331 27268 29756 43848 33671 25923 32892 31319
 39374 44212 29560 36356 40026 40345 39323 36305 42060 42212 29795 30559
 46630 34408 48441 46918 28634 48644 39317 36781 25265 36375 47455 37267
 30942 41734 45897 39347 38396 34466 34398 46452 25400 26481 28217 47526
 43759 48594 27921 48234 38905 39736 27753 28841 37442 40198 36465 41649
 45895 25900 45709 43658 25441 29582 30906 44814 49512 41754 47921 38693
 33958 29525 32715 49338 25260 32546 40063 46508 34732 45902 42534 30422
 48397 36848 31534 27455 40055 32473 26012 43540 41803 26529 46085 47342
 36822 32013 45230 36360 36965 30261 25602 48441 36393 47238 26486 34834
 33072 33514 43551 32690 46341 41926 29649 30376 40583 41407 41346 38674
 35218 41361 26258 43363 46870 27603 29152 41345 37305 42219 34027 28404
 42643 30393 49806 48596 41236 40959 25254 36571 25593 36849 40236 45153
 33790 34801 40814 44917 31513 32622 42872 41292 39501 37427 49829 43122
 27276 39053 47309 32318 43669 27699 35115 26864 33289 40467 44215 44486
 43242 39965 31893 37522 46567 41592 42345 41345 31326 41601 26345 48454
 30335 42507 29251 47432 42962 30316 38024 34924 48758 26821 43013 30784
 38621 29178 40809 38765 40313 48908 29352 37430 45039 28114 42309 37412
 32394 42682 31865 28033 41887 29502 49397 41810 27838 41048 39763 39466
 37852 31961 27121 25480 34013 48205 38434 39253 46043 35984 35879 48069
 38593 27077 47802 26671 32991 35341 35185 46818 25892 29170 35159 49217
 49901 35546 39664 41391 29194 41918 30468 46567 36773 47202 25466 27260
 48795 44874 34495 26285 44348 26272 36865 47863 27470 26011 44336 28808
 35833 31027 41848 29014 26559 46230 43275 35665 39264 45974 27690 49267
 26115 30668 38629 32322 26970 27780 37669 31528 31245 37257 25558 44602
 46246 48377 29988 27671 35346 33075 35810 29578 42731 35529 25288 49499
 31210 39490 29229 39465 42179 36583 38981 34848 37155 38587 28586 35637
 29075 31130 37567 41441 28785 47821 43579 42981 26610 43563 33473 45264
 37037 46947 26695 33495 26903 48860 39698 31792 33362 37946 30201 28920
 46660 29601 44427 47621 37109 31983 25670 32340 28841 30730 26721 42908
 38998 45099 25955 47379 37220 31961 29259 35769 43634 35417 29754 40397
 40030 34221 28258 26200 49977 45314 41036 39727 32392 30655 26242 47866
 26829 43096 49107 48547 40644 31831 30814 27650]

Finance salary= [59010.   59543.75 31885.   48233.75 47941.25 53591.25 52737.5  42155.
 60641.25 58682.5  43756.25 46702.5  46415.   41770.   31931.25 60836.25
 46868.75 36008.75 47880.   45272.5  44925.   34137.5  58925.   60623.75
 44367.5  53228.75 43636.25 50967.5  52657.5  33925.   33746.25 60538.75
 42881.25 34428.75 57090.   32805.   44241.25 52927.5  59220.   43816.25
 31787.5  53752.5  46870.   37171.25 53768.75 57730.   45786.25 32906.25
 31555.   62457.5  51161.25 48792.5  54188.75 39330.   43376.25 52738.75
 43406.25 38057.5  50800.   33425.   53961.25 46086.25 34931.25 61641.25
 35705.   61355.   59683.75 33862.5  53350.   38232.5  46933.75 40738.75
 41857.5  32241.25 53025.   37071.25 55966.25 34623.75 49156.25 37145.
 40203.75 37595.   39275.   45952.5  39096.25 45918.75 61287.5  54997.5
 44300.   32750.   59888.75 59998.75 36590.   56281.25 48932.5  53786.25
 41186.25 55060.   50848.75 38798.75 37501.25 37471.25 43545.   44597.5
 60525.   61822.5  58900.   60411.25 49360.   48883.75 57360.   45841.25
 40900.   36302.5  34580.   60526.25 45220.   47363.75 33657.5  43140.
 45778.75 34061.25 62291.25 36543.75 32913.75 34085.   37195.   54810.
 42088.75 32403.75 41115.   39148.75 49217.5  55265.   36950.   45445.
 50032.5  50431.25 49153.75 45381.25 52575.   52765.   37243.75 38198.75
 58287.5  43010.   60551.25 58647.5  35792.5  60805.   49146.25 45976.25
 31581.25 45468.75 59318.75 46583.75 38677.5  52167.5  57371.25 49183.75
 47995.   43082.5  42997.5  58065.   31750.   33101.25 35271.25 59407.5
 54698.75 60742.5  34901.25 60292.5  48631.25 49670.   34691.25 36051.25
 46802.5  50247.5  45581.25 52061.25 57368.75 32375.   57136.25 54572.5
 31801.25 36977.5  38632.5  56017.5  61890.   52192.5  59901.25 48366.25
 42447.5  36906.25 40893.75 61672.5  31575.   40682.5  50078.75 58135.
 43415.   57377.5  53167.5  38027.5  60496.25 46060.   39417.5  34318.75
 50068.75 40591.25 32515.   54425.   52253.75 33161.25 57606.25 59177.5
 46027.5  40016.25 56537.5  45450.   46206.25 37826.25 32002.5  60551.25
 45491.25 59047.5  33107.5  43542.5  41340.   41892.5  54438.75 40862.5
 57926.25 52407.5  37061.25 37970.   50728.75 51758.75 51682.5  48342.5
 44022.5  51701.25 32822.5  54203.75 58587.5  34503.75 36440.   51681.25
 46631.25 52773.75 42533.75 35505.   53303.75 37991.25 62257.5  60745.
 51545.   51198.75 31567.5  45713.75 31991.25 46061.25 50295.   56441.25
 42237.5  43501.25 51017.5  56146.25 39391.25 40777.5  53590.   51615.
 49376.25 46783.75 62286.25 53902.5  34095.   48816.25 59136.25 40397.5
 54586.25 34623.75 43893.75 33580.   41611.25 50583.75 55268.75 55607.5
 54052.5  49956.25 39866.25 46902.5  58208.75 51990.   52931.25 51681.25
 39157.5  52001.25 32931.25 60567.5  37918.75 53133.75 36563.75 59290.
 53702.5  37895.   47530.   43655.   60947.5  33526.25 53766.25 38480.
 48276.25 36472.5  51011.25 48456.25 50391.25 61135.   36690.   46787.5
 56298.75 35142.5  52886.25 46765.   40492.5  53352.5  39831.25 35041.25
 52358.75 36877.5  61746.25 52262.5  34797.5  51310.   49703.75 49332.5
 47315.   39951.25 33901.25 31850.   42516.25 60256.25 48042.5  49066.25
 57553.75 44980.   44848.75 60086.25 48241.25 33846.25 59752.5  33338.75
 41238.75 44176.25 43981.25 58522.5  32365.   36462.5  43948.75 61521.25
 62376.25 44432.5  49580.   51738.75 36492.5  52397.5  38085.   58208.75
 45966.25 59002.5  31832.5  34075.   60993.75 56092.5  43118.75 32856.25
 55435.   32840.   46081.25 59828.75 34337.5  32513.75 55420.   36010.
 44791.25 38783.75 52310.   36267.5  33198.75 57787.5  54093.75 44581.25
 49080.   57467.5  34612.5  61583.75 32643.75 38335.   48286.25 40402.5
 33712.5  34725.   47086.25 39410.   39056.25 46571.25 31947.5  55752.5
 57807.5  60471.25 37485.   34588.75 44182.5  41343.75 44762.5  36972.5
 53413.75 44411.25 31610.   61873.75 39012.5  49362.5  36536.25 49331.25
 52723.75 45728.75 48726.25 43560.   46443.75 48233.75 35732.5  44546.25
 36343.75 38912.5  46958.75 51801.25 35981.25 59776.25 54473.75 53726.25
 33262.5  54453.75 41841.25 56580.   46296.25 58683.75 33368.75 41868.75
 33628.75 61075.   49622.5  39740.   41702.5  47432.5  37751.25 36150.
 58325.   37001.25 55533.75 59526.25 46386.25 39978.75 32087.5  40425.
 36051.25 38412.5  33401.25 53635.   48747.5  56373.75 32443.75 59223.75
 46525.   39951.25 36573.75 44711.25 54542.5  44271.25 37192.5  50496.25
 50037.5  42776.25 35322.5  32750.   62471.25 56642.5  51295.   49658.75
 40490.   38318.75 32802.5  59832.5  33536.25 53870.   61383.75 60683.75
 50805.   39788.75 38517.5  34562.5 ]

Sales salary= [29505.    29771.875 15942.5   24116.875 23970.625 26795.625 26368.75
 21077.5   30320.625 29341.25  21878.125 23351.25  23207.5   20885.
 15965.625 30418.125 23434.375 18004.375 23940.    22636.25  22462.5
 17068.75  29462.5   30311.875 22183.75  26614.375 21818.125 25483.75
 26328.75  16962.5   16873.125 30269.375 21440.625 17214.375 28545.
 16402.5   22120.625 26463.75  29610.    21908.125 15893.75  26876.25
 23435.    18585.625 26884.375 28865.    22893.125 16453.125 15777.5
 31228.75  25580.625 24396.25  27094.375 19665.    21688.125 26369.375
 21703.125 19028.75  25400.    16712.5   26980.625 23043.125 17465.625
 30820.625 17852.5   30677.5   29841.875 16931.25  26675.    19116.25
 23466.875 20369.375 20928.75  16120.625 26512.5   18535.625 27983.125
 17311.875 24578.125 18572.5   20101.875 18797.5   19637.5   22976.25
 19548.125 22959.375 30643.75  27498.75  22150.    16375.    29944.375
 29999.375 18295.    28140.625 24466.25  26893.125 20593.125 27530.
 25424.375 19399.375 18750.625 18735.625 21772.5   22298.75  30262.5
 30911.25  29450.    30205.625 24680.    24441.875 28680.    22920.625
 20450.    18151.25  17290.    30263.125 22610.    23681.875 16828.75
 21570.    22889.375 17030.625 31145.625 18271.875 16456.875 17042.5
 18597.5   27405.    21044.375 16201.875 20557.5   19574.375 24608.75
 27632.5   18475.    22722.5   25016.25  25215.625 24576.875 22690.625
 26287.5   26382.5   18621.875 19099.375 29143.75  21505.    30275.625
 29323.75  17896.25  30402.5   24573.125 22988.125 15790.625 22734.375
 29659.375 23291.875 19338.75  26083.75  28685.625 24591.875 23997.5
 21541.25  21498.75  29032.5   15875.    16550.625 17635.625 29703.75
 27349.375 30371.25  17450.625 30146.25  24315.625 24835.    17345.625
 18025.625 23401.25  25123.75  22790.625 26030.625 28684.375 16187.5
 28568.125 27286.25  15900.625 18488.75  19316.25  28008.75  30945.
 26096.25  29950.625 24183.125 21223.75  18453.125 20446.875 30836.25
 15787.5   20341.25  25039.375 29067.5   21707.5   28688.75  26583.75
 19013.75  30248.125 23030.    19708.75  17159.375 25034.375 20295.625
 16257.5   27212.5   26126.875 16580.625 28803.125 29588.75  23013.75
 20008.125 28268.75  22725.    23103.125 18913.125 16001.25  30275.625
 22745.625 29523.75  16553.75  21771.25  20670.    20946.25  27219.375
 20431.25  28963.125 26203.75  18530.625 18985.    25364.375 25879.375
 25841.25  24171.25  22011.25  25850.625 16411.25  27101.875 29293.75
 17251.875 18220.    25840.625 23315.625 26386.875 21266.875 17752.5
 26651.875 18995.625 31128.75  30372.5   25772.5   25599.375 15783.75
 22856.875 15995.625 23030.625 25147.5   28220.625 21118.75  21750.625
 25508.75  28073.125 19695.625 20388.75  26795.    25807.5   24688.125
 23391.875 31143.125 26951.25  17047.5   24408.125 29568.125 20198.75
 27293.125 17311.875 21946.875 16790.    20805.625 25291.875 27634.375
 27803.75  27026.25  24978.125 19933.125 23451.25  29104.375 25995.
 26465.625 25840.625 19578.75  26000.625 16465.625 30283.75  18959.375
 26566.875 18281.875 29645.    26851.25  18947.5   23765.    21827.5
 30473.75  16763.125 26883.125 19240.    24138.125 18236.25  25505.625
 24228.125 25195.625 30567.5   18345.    23393.75  28149.375 17571.25
 26443.125 23382.5   20246.25  26676.25  19915.625 17520.625 26179.375
 18438.75  30873.125 26131.25  17398.75  25655.    24851.875 24666.25
 23657.5   19975.625 16950.625 15925.    21258.125 30128.125 24021.25
 24533.125 28776.875 22490.    22424.375 30043.125 24120.625 16923.125
 29876.25  16669.375 20619.375 22088.125 21990.625 29261.25  16182.5
 18231.25  21974.375 30760.625 31188.125 22216.25  24790.    25869.375
 18246.25  26198.75  19042.5   29104.375 22983.125 29501.25  15916.25
 17037.5   30496.875 28046.25  21559.375 16428.125 27717.5   16420.
 23040.625 29914.375 17168.75  16256.875 27710.    18005.    22395.625
 19391.875 26155.    18133.75  16599.375 28893.75  27046.875 22290.625
 24540.    28733.75  17306.25  30791.875 16321.875 19167.5   24143.125
 20201.25  16856.25  17362.5   23543.125 19705.    19528.125 23285.625
 15973.75  27876.25  28903.75  30235.625 18742.5   17294.375 22091.25
 20671.875 22381.25  18486.25  26706.875 22205.625 15805.    30936.875
 19506.25  24681.25  18268.125 24665.625 26361.875 22864.375 24363.125
 21780.    23221.875 24116.875 17866.25  22273.125 18171.875 19456.25
 23479.375 25900.625 17990.625 29888.125 27236.875 26863.125 16631.25
 27226.875 20920.625 28290.    23148.125 29341.875 16684.375 20934.375
 16814.375 30537.5   24811.25  19870.    20851.25  23716.25  18875.625
 18075.    29162.5   18500.625 27766.875 29763.125 23193.125 19989.375
 16043.75  20212.5   18025.625 19206.25  16700.625 26817.5   24373.75
 28186.875 16221.875 29611.875 23262.5   19975.625 18286.875 22355.625
 27271.25  22135.625 18596.25  25248.125 25018.75  21388.125 17661.25
 16375.    31235.625 28321.25  25647.5   24829.375 20245.    19159.375
 16401.25  29916.25  16768.125 26935.    30691.875 30341.875 25402.5
 19894.375 19258.75  17281.25 ]

IT salary= [52208 52635 30508 43587 43353 47873 47190 38724 53513 51946 40005 42362
 42132 38416 30545 53669 42495 33807 43304 41218 40940 32310 52140 53499
 40494 47583 39909 45774 47126 32140 31997 53431 39305 32543 50672 31244
 40393 47342 52376 40053 30430 48002 42496 34737 48015 51184 41629 31325
 30244 54966 45929 44034 48351 36464 39701 47191 39725 35446 45640 31740
 48169 41869 32945 54313 33564 54084 52747 32090 47680 35586 42547 37591
 38486 30793 47420 34657 49773 32699 44325 34716 37163 35076 36420 41762
 36277 41735 54030 48998 40440 31200 52911 52999 34272 50025 44146 48029
 37949 49048 45679 36039 35001 34977 39836 40678 53420 54458 52120 53329
 44488 44107 50888 41673 37720 34042 32664 53421 41176 42891 31926 39512
 41623 32249 54833 34235 31331 32268 34756 48848 38671 30923 37892 36319
 44374 49212 34560 41356 45026 45345 44323 41305 47060 47212 34795 35559
 51630 39408 53441 51918 33634 53644 44317 41781 30265 41375 52455 42267
 35942 46734 50897 44347 43396 39466 39398 51452 30400 31481 33217 52526
 48759 53594 32921 53234 43905 44736 32753 33841 42442 45198 41465 46649
 50895 30900 50709 48658 30441 34582 35906 49814 54512 46754 52921 43693
 38958 34525 37715 54338 30260 37546 45063 51508 39732 50902 47534 35422
 53397 41848 36534 32455 45055 37473 31012 48540 46803 31529 51085 52342
 41822 37013 50230 41360 41965 35261 30602 53441 41393 52238 31486 39834
 38072 38514 48551 37690 51341 46926 34649 35376 45583 46407 46346 43674
 40218 46361 31258 48363 51870 32603 34152 46345 42305 47219 39027 33404
 47643 35393 54806 53596 46236 45959 30254 41571 30593 41849 45236 50153
 38790 39801 45814 49917 36513 37622 47872 46292 44501 42427 54829 48122
 32276 44053 52309 37318 48669 32699 40115 31864 38289 45467 49215 49486
 48242 44965 36893 42522 51567 46592 47345 46345 36326 46601 31345 53454
 35335 47507 34251 52432 47962 35316 43024 39924 53758 31821 48013 35784
 43621 34178 45809 43765 45313 53908 34352 42430 50039 33114 47309 42412
 37394 47682 36865 33033 46887 34502 54397 46810 32838 46048 44763 44466
 42852 36961 32121 30480 39013 53205 43434 44253 51043 40984 40879 53069
 43593 32077 52802 31671 37991 40341 40185 51818 30892 34170 40159 54217
 54901 40546 44664 46391 34194 46918 35468 51567 41773 52202 30466 32260
 53795 49874 39495 31285 49348 31272 41865 52863 32470 31011 49336 33808
 40833 36027 46848 34014 31559 51230 48275 40665 44264 50974 32690 54267
 31115 35668 43629 37322 31970 32780 42669 36528 36245 42257 30558 49602
 51246 53377 34988 32671 40346 38075 40810 34578 47731 40529 30288 54499
 36210 44490 34229 44465 47179 41583 43981 39848 42155 43587 33586 40637
 34075 36130 42567 46441 33785 52821 48579 47981 31610 48563 38473 50264
 42037 51947 31695 38495 31903 53860 44698 36792 38362 42946 35201 33920
 51660 34601 49427 52621 42109 36983 30670 37340 33841 35730 31721 47908
 43998 50099 30955 52379 42220 36961 34259 40769 48634 40417 34754 45397
 45030 39221 33258 31200 54977 50314 46036 44727 37392 35655 31242 52866
 31829 48096 54107 53547 45644 36831 35814 32650]

In [4]:
# TASK 3
a_sum=np.sum(HR_salary)
print('Sum of HR=',a_sum)
b_sum=np.sum(Finance_salary)
print('Sum of Finance=',b_sum)
c_sum=np.sum(Sales_salary)
print('Sum of Sales=',c_sum)
d_sum=np.sum(IT_salary)
print('Sum of IT=',d_sum)
if a_sum>b_sum:
    print('HR is costing higher')
elif b_sum>c_sum:
    print('Finance is costing higher')
elif c_sum>d_sum:
    print('Sales is costing higher')
elif d_sum>a_sum:
    print('IT is costing higher')

Sum of HR= 18544713
Sum of Finance= 23180891.25
Sum of Sales= 11590445.625
Sum of IT= 21044713
Finance is costing higher

In [5]:
# TASK 4
HR_high=np.sort(HR_salary)[::-1]
a=HR_high[0:10]
print('Highest salary of HR department=',a)
Finance_high=np.sort(Finance_salary)[::-1]
b=Finance_high[0:10]
print('Highest salary of Finance department=',b)
Sales_high=np.sort(Sales_salary)[::-1]
c=Sales_high[0:10]
print('Highest salary of Sales department=',c)
IT_high=np.sort(IT_salary)[::-1]
d=IT_high[0:10]
print('Highest salary of IT department=',d)
print()
a=np.sum(a)
print('Sum of HR=',a)
b=np.sum(b)
print('Sum of Finance=',b)
c=np.sum(c)
print('Sum of Sales=',c)
d=np.sum(d)
print('Sum of IT=',d)

Highest salary of HR department= [49977 49966 49901 49833 49829 49806 49512 49499 49458 49397]
Highest salary of Finance department= [62471.25 62457.5  62376.25 62291.25 62286.25 62257.5  61890.   61873.75
 61822.5  61746.25]
Highest salary of Sales department= [31235.625 31228.75  31188.125 31145.625 31143.125 31128.75  30945.
 30936.875 30911.25  30873.125]
Highest salary of IT department= [54977 54966 54901 54833 54829 54806 54512 54499 54458 54397]

Sum of HR= 497178
Sum of Finance= 621472.5
Sum of Sales= 310736.25
Sum of IT= 547178

In [6]:
# TASK 5
a=np.count_nonzero(HR_salary>45000)
print('No.of employee in HR whose salary is higher than 45,000 is',a)
b=np.count_nonzero(Finance_salary>45000)
print('No.of employee in Finance whose salary is higher than 45,000 is',b)
c=np.count_nonzero(Sales_salary>45000)
print('No.of employee in Sales whose salary is higher than 45,000 is',c)
d=np.count_nonzero(IT_salary>45000)
print('No.of employee in IT whose salary is higher than 45,000 is',d)
print()
print('Total no.of employee whose salary is higher than 45,000 is',a+b+c+d)

No.of employee in HR whose salary is higher than 45,000 is 93
No.of employee in Finance whose salary is higher than 45,000 is 273
No.of employee in Sales whose salary is higher than 45,000 is 0
No.of employee in IT whose salary is higher than 45,000 is 190

Total no.of employee whose salary is higher than 45,000 is 556

In [7]:
# TASK 6
ind=np.where(Sales_salary<20000)
new_sales=Sales_salary[ind]*1.2
print(new_sales)

[19131.   19158.75 21605.25 20482.5  20355.   20247.75 20657.25 19683.
 19072.5  22302.75 19743.75 18933.   23598.   22834.5  20055.   20958.75
 21423.   20317.5  22939.5  19344.75 22242.75 20774.25 22287.   22557.
 23565.   23457.75 19650.   21954.   23279.25 22500.75 22482.75 21781.5
 20748.   20194.5  20436.75 21926.25 19748.25 20451.   22317.   19442.25
 23489.25 22170.   22346.25 22919.25 21475.5  18948.75 23206.5  19050.
 19860.75 21162.75 20940.75 20814.75 21630.75 19425.   19080.75 22186.5
 23179.5  22143.75 18945.   22816.5  23650.5  20591.25 19509.   19896.75
 22695.75 19201.5  19864.5  22236.75 22782.   19693.5  20702.25 21864.
 21303.   22794.75 18940.5  19194.75 23634.75 20457.   20774.25 20148.
 23919.75 23494.5  19758.75 22751.25 21938.25 22737.   20115.75 23088.
 21883.5  22014.   21085.5  23898.75 21024.75 22126.5  20878.5  23970.75
 20340.75 19110.   20307.75 20003.25 19419.   21877.5  21895.5  22851.
 19099.5  20445.   19713.75 19704.   20602.5  19508.25 21606.   23270.25
 21760.5  19919.25 20767.5  19586.25 23001.   20227.5  20835.   23646.
 23433.75 19168.5  22491.   20753.25 22183.5  18966.   23407.5  21921.75
 21439.5  21806.25 23347.5  21588.75 19957.5  20021.25 20177.25 23844.
 22650.75 21690.   22200.75 23987.25 19252.5  21630.75 23047.5  20040.75
 19466.25 23970.75 21944.25 22315.5  21193.5  19650.   22991.25 19681.5
 20121.75 23873.25 23110.5  20737.5 ]

In [8]:
# TASK 7
emp=np.where(Sales>=1996)
print(emp)
Sales=np.delete(Sales, emp)
a=Sales
print(a)
Sales_1=np.arange(2001,2006)
Sales=np.append(Sales,Sales_1)
Sales

(array([495, 496, 497, 498, 499], dtype=int64),)
[1501 1502 1503 1504 1505 1506 1507 1508 1509 1510 1511 1512 1513 1514
 1515 1516 1517 1518 1519 1520 1521 1522 1523 1524 1525 1526 1527 1528
 1529 1530 1531 1532 1533 1534 1535 1536 1537 1538 1539 1540 1541 1542
 1543 1544 1545 1546 1547 1548 1549 1550 1551 1552 1553 1554 1555 1556
 1557 1558 1559 1560 1561 1562 1563 1564 1565 1566 1567 1568 1569 1570
 1571 1572 1573 1574 1575 1576 1577 1578 1579 1580 1581 1582 1583 1584
 1585 1586 1587 1588 1589 1590 1591 1592 1593 1594 1595 1596 1597 1598
 1599 1600 1601 1602 1603 1604 1605 1606 1607 1608 1609 1610 1611 1612
 1613 1614 1615 1616 1617 1618 1619 1620 1621 1622 1623 1624 1625 1626
 1627 1628 1629 1630 1631 1632 1633 1634 1635 1636 1637 1638 1639 1640
 1641 1642 1643 1644 1645 1646 1647 1648 1649 1650 1651 1652 1653 1654
 1655 1656 1657 1658 1659 1660 1661 1662 1663 1664 1665 1666 1667 1668
 1669 1670 1671 1672 1673 1674 1675 1676 1677 1678 1679 1680 1681 1682
 1683 1684 1685 1686 1687 1688 1689 1690 1691 1692 1693 1694 1695 1696
 1697 1698 1699 1700 1701 1702 1703 1704 1705 1706 1707 1708 1709 1710
 1711 1712 1713 1714 1715 1716 1717 1718 1719 1720 1721 1722 1723 1724
 1725 1726 1727 1728 1729 1730 1731 1732 1733 1734 1735 1736 1737 1738
 1739 1740 1741 1742 1743 1744 1745 1746 1747 1748 1749 1750 1751 1752
 1753 1754 1755 1756 1757 1758 1759 1760 1761 1762 1763 1764 1765 1766
 1767 1768 1769 1770 1771 1772 1773 1774 1775 1776 1777 1778 1779 1780
 1781 1782 1783 1784 1785 1786 1787 1788 1789 1790 1791 1792 1793 1794
 1795 1796 1797 1798 1799 1800 1801 1802 1803 1804 1805 1806 1807 1808
 1809 1810 1811 1812 1813 1814 1815 1816 1817 1818 1819 1820 1821 1822
 1823 1824 1825 1826 1827 1828 1829 1830 1831 1832 1833 1834 1835 1836
 1837 1838 1839 1840 1841 1842 1843 1844 1845 1846 1847 1848 1849 1850
 1851 1852 1853 1854 1855 1856 1857 1858 1859 1860 1861 1862 1863 1864
 1865 1866 1867 1868 1869 1870 1871 1872 1873 1874 1875 1876 1877 1878
 1879 1880 1881 1882 1883 1884 1885 1886 1887 1888 1889 1890 1891 1892
 1893 1894 1895 1896 1897 1898 1899 1900 1901 1902 1903 1904 1905 1906
 1907 1908 1909 1910 1911 1912 1913 1914 1915 1916 1917 1918 1919 1920
 1921 1922 1923 1924 1925 1926 1927 1928 1929 1930 1931 1932 1933 1934
 1935 1936 1937 1938 1939 1940 1941 1942 1943 1944 1945 1946 1947 1948
 1949 1950 1951 1952 1953 1954 1955 1956 1957 1958 1959 1960 1961 1962
 1963 1964 1965 1966 1967 1968 1969 1970 1971 1972 1973 1974 1975 1976
 1977 1978 1979 1980 1981 1982 1983 1984 1985 1986 1987 1988 1989 1990
 1991 1992 1993 1994 1995]

array([1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1510, 1511,
       1512, 1513, 1514, 1515, 1516, 1517, 1518, 1519, 1520, 1521, 1522,
       1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530, 1531, 1532, 1533,
       1534, 1535, 1536, 1537, 1538, 1539, 1540, 1541, 1542, 1543, 1544,
       1545, 1546, 1547, 1548, 1549, 1550, 1551, 1552, 1553, 1554, 1555,
       1556, 1557, 1558, 1559, 1560, 1561, 1562, 1563, 1564, 1565, 1566,
       1567, 1568, 1569, 1570, 1571, 1572, 1573, 1574, 1575, 1576, 1577,
       1578, 1579, 1580, 1581, 1582, 1583, 1584, 1585, 1586, 1587, 1588,
       1589, 1590, 1591, 1592, 1593, 1594, 1595, 1596, 1597, 1598, 1599,
       1600, 1601, 1602, 1603, 1604, 1605, 1606, 1607, 1608, 1609, 1610,
       1611, 1612, 1613, 1614, 1615, 1616, 1617, 1618, 1619, 1620, 1621,
       1622, 1623, 1624, 1625, 1626, 1627, 1628, 1629, 1630, 1631, 1632,
       1633, 1634, 1635, 1636, 1637, 1638, 1639, 1640, 1641, 1642, 1643,
       1644, 1645, 1646, 1647, 1648, 1649, 1650, 1651, 1652, 1653, 1654,
       1655, 1656, 1657, 1658, 1659, 1660, 1661, 1662, 1663, 1664, 1665,
       1666, 1667, 1668, 1669, 1670, 1671, 1672, 1673, 1674, 1675, 1676,
       1677, 1678, 1679, 1680, 1681, 1682, 1683, 1684, 1685, 1686, 1687,
       1688, 1689, 1690, 1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698,
       1699, 1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708, 1709,
       1710, 1711, 1712, 1713, 1714, 1715, 1716, 1717, 1718, 1719, 1720,
       1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1731,
       1732, 1733, 1734, 1735, 1736, 1737, 1738, 1739, 1740, 1741, 1742,
       1743, 1744, 1745, 1746, 1747, 1748, 1749, 1750, 1751, 1752, 1753,
       1754, 1755, 1756, 1757, 1758, 1759, 1760, 1761, 1762, 1763, 1764,
       1765, 1766, 1767, 1768, 1769, 1770, 1771, 1772, 1773, 1774, 1775,
       1776, 1777, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1785, 1786,
       1787, 1788, 1789, 1790, 1791, 1792, 1793, 1794, 1795, 1796, 1797,
       1798, 1799, 1800, 1801, 1802, 1803, 1804, 1805, 1806, 1807, 1808,
       1809, 1810, 1811, 1812, 1813, 1814, 1815, 1816, 1817, 1818, 1819,
       1820, 1821, 1822, 1823, 1824, 1825, 1826, 1827, 1828, 1829, 1830,
       1831, 1832, 1833, 1834, 1835, 1836, 1837, 1838, 1839, 1840, 1841,
       1842, 1843, 1844, 1845, 1846, 1847, 1848, 1849, 1850, 1851, 1852,
       1853, 1854, 1855, 1856, 1857, 1858, 1859, 1860, 1861, 1862, 1863,
       1864, 1865, 1866, 1867, 1868, 1869, 1870, 1871, 1872, 1873, 1874,
       1875, 1876, 1877, 1878, 1879, 1880, 1881, 1882, 1883, 1884, 1885,
       1886, 1887, 1888, 1889, 1890, 1891, 1892, 1893, 1894, 1895, 1896,
       1897, 1898, 1899, 1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907,
       1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918,
       1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929,
       1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940,
       1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951,
       1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962,
       1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973,
       1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984,
       1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995,
       2001, 2002, 2003, 2004, 2005])

In [9]:
# ADDITIONAL QUESTIONS

In [35]:
# TASK 8
# Percentage
Total_salary=((a_sum-c_sum)/a_sum)*100
print('The Total salary of HR department is',Total_salary,'%','more than Sales department')
# difference
Avg_HR=np.mean(HR_salary)
Avg_Sales=np.mean(Sales_salary)
diff=Avg_HR-Avg_Sales
print('Difference between the average salary of HR and Sales department=',diff)

The Total salary of HR department is 37.5 % more than Sales department
Difference between the average salary of HR and Sales department= 13908.534749999999

In [12]:
# TASK 9

Emp=np.where((Finance_salary >=50000) & (Finance_salary <=55000))
# print(Emp)
count=np.count_nonzero(Emp)
print('Total no.of employee getting salary between 50,000 and 55,000 in sales department is',count)

Total no.of employee getting salary between 50,000 and 55,000 in sales department is 85

In [13]:
pwd

'C:\\Users\\Admin\\Umayal.M_DSFT4_C4\\Umayal.M_DSFT4_C4_S1'

In [36]:
# TASK 10
import numpy as np
from numpy import genfromtxt
code=genfromtxt("C:\\Users\\Admin\\a.csv",delimiter=',',skip_header=1)
# print(code)
x=code.T
print('Average age of employees=',np.mean(x[1]))

Average age of employees= 28.26

In [37]:
# TASK 11
age=np.count_nonzero(x[1]>25)
print('Total no.of employees whose age is more than 25 is',age)
y=np.where(code[:,1]>25)
print('Employee whose age is above 25 is',code[y])

Total no.of employees whose age is more than 25 is 38
Employee whose age is above 25 is [[ 2. 27.]
 [ 3. 31.]
 [ 4. 29.]
 [ 5. 27.]
 [ 6. 26.]
 [ 7. 27.]
 [ 9. 27.]
 [10. 32.]
 [11. 28.]
 [12. 27.]
 [14. 27.]
 [15. 35.]
 [16. 33.]
 [17. 28.]
 [20. 27.]
 [21. 37.]
 [22. 27.]
 [24. 27.]
 [25. 28.]
 [26. 26.]
 [27. 27.]
 [28. 27.]
 [29. 29.]
 [30. 49.]
 [31. 26.]
 [32. 32.]
 [33. 26.]
 [37. 28.]
 [38. 28.]
 [40. 26.]
 [41. 32.]
 [42. 35.]
 [43. 33.]
 [44. 31.]
 [45. 30.]
 [46. 36.]
 [49. 32.]
 [50. 34.]]

In [38]:
# TASK 12
age=np.count_nonzero((x[1]>30) & (x[1]<35))
print('Total no.of employees whose age is more than 30 and less than 35 is',age)
s=np.where((code[:,1]>30) & (code[:,1]<35))
print('Employee whose age is above 30 and less than 35 is',code[s])

Total no.of employees whose age is more than 30 and less than 35 is 9
Employee whose age is above 30 and less than 35 is [[ 3. 31.]
 [10. 32.]
 [16. 33.]
 [32. 32.]
 [41. 32.]
 [43. 33.]
 [44. 31.]
 [49. 32.]
 [50. 34.]]

In [ ]:
# END